# Generated by Django 3.2.8 on 2021-10-14 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_Address', models.TextField()),
                ('Longitude', models.TextField()),
                ('Latitude', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'userinfo',
                'verbose_name_plural': 'userinfos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
