# Generated by Django 3.2.9 on 2022-01-11 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='onemarchant_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('userlevel', models.TextField()),
            ],
            options={
                'verbose_name': 'onemarchant_user',
                'verbose_name_plural': 'onemarchant_users',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('ip_Address', models.TextField()),
                ('Longitude', models.TextField()),
                ('Latitude', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('logout_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'userinfo',
                'verbose_name_plural': 'userinfos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
