# Generated by Django 3.2.9 on 2022-01-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='onemarchant_user',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='userlevel',
        ),
    ]
