# Generated by Django 3.2.8 on 2021-10-17 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_memos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='logout_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
