# Generated by Django 3.2.8 on 2021-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinfo_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
