# Generated by Django 3.2.9 on 2022-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdby_id', models.IntegerField()),
                ('memo', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'memos',
                'verbose_name_plural': 'memos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
