# Generated by Django 3.2.9 on 2022-01-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_request',
            name='approved_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car_request',
            name='assigned_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
