# Generated by Django 3.2.9 on 2022-01-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rides', '0002_auto_20220112_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_request',
            name='rejected_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_request',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_request',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
