# Generated by Django 3.2.9 on 2021-11-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=250)),
                ('assigned_to', models.IntegerField()),
                ('tax_renewed_date', models.DateField(blank=True, null=True)),
                ('tax_expiration_date', models.DateField(blank=True, null=True)),
                ('fitness_renewed_date', models.DateField(blank=True, null=True)),
                ('fitness_expiration_date', models.DateField(blank=True, null=True)),
                ('car_maintanance_date', models.DateField(blank=True, null=True)),
                ('car_condition', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'cars',
                'verbose_name_plural': 'carss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
