# Generated by Django 3.2.8 on 2021-10-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=250)),
                ('assigned_to', models.IntegerField()),
            ],
            options={
                'verbose_name': 'cars',
                'verbose_name_plural': 'carss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
