# Generated by Django 3.2.8 on 2021-10-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assigned_to', models.IntegerField()),
            ],
            options={
                'verbose_name': 'tasks',
                'verbose_name_plural': 'taskss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
