# Generated by Django 3.2.9 on 2021-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
