# Generated by Django 3.2.9 on 2021-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
