# Generated by Django 3.2.9 on 2021-11-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='timer',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
