# Generated by Django 3.2.9 on 2021-11-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20211116_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='timer',
            new_name='end_timer',
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_timer',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
