# Generated by Django 3.2.8 on 2021-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('notification', models.CharField(max_length=255)),
                ('notification_type', models.IntegerField()),
            ],
            options={
                'verbose_name': 'notifications',
                'verbose_name_plural': 'notificationss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
