# Generated by Django 3.2.9 on 2021-11-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
