# Generated by Django 3.2.9 on 2021-11-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(default='New', max_length=255),
        ),
    ]
